services:
  postgres:
    image: postgres:latest

    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db-frknz
      POSTGRES_DB: example

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on: 
    - postgres

    ports:

  nginx:
    image: nginx:latest

    volumes:
    - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"

    depends_on:
      - backend 

volumes:
  postgres_data: